=== Marcos-Oleiro/concursoWEB3/src/lib/candidate_final.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


		<xs:simpleType name="answer">
			<xs:restriction base="xs:string">
				<xs:pattern value="(A|B|C|D|E|N){1}"></xs:pattern>
			</xs:restriction>
		</xs:simpleType>
		
		<xs:complexType name="port_test">
			<xs:sequence>
				<xs:element name="pq1" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq2" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq3" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq4" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq5" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq6" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq7" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq8" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq9" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq10" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq11" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq12" type="answer" minOccurs="1" maxOccurs="1" /> 
				<xs:element name="pq13" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq14" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="pq15" type="answer" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
		
		<xs:complexType name="math_test">
			<xs:sequence>
				<xs:element name="mq1" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq2" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq3" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq4" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq5" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq6" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq7" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq8" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq9" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq10" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq11" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq12" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq13" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="mq14" type="answer" minOccurs="1" maxOccurs="1" /> 
				<xs:element name="mq15" type="answer" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
				
		<xs:complexType name="spec_test">
			<xs:sequence>
				<xs:element name="sq1" type="answer" minOccurs="1" maxOccurs="1" /> 
				<xs:element name="sq2" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq3" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq4" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq5" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq6" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq7" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq8" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq9" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq10" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq11" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq12" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq13" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq14" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq15" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq16" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq17" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq18" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq19" type="answer" minOccurs="1" maxOccurs="1" />
				<xs:element name="sq20" type="answer" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
		
	<xs:element name="candidate">
			
			<xs:complexType >
				<xs:sequence>
					<xs:element name="registration_number" type="xs:integer" minOccurs="1" maxOccurs="1" />
					<xs:element name="registration_date" type="xs:date" minOccurs="1" maxOccurs="1" />
					<xs:element name="position" type="xs:string" minOccurs="1" maxOccurs="1" />
					<xs:element name="port_test" type="port_test" minOccurs="1" maxOccurs="1" />
					<xs:element name="math_test" type="math_test" minOccurs="1" maxOccurs="1" />
					<xs:element name="spec_test" type="spec_test" minOccurs="1" maxOccurs="1" />
					<xs:element name="port_count" type="xs:integer" minOccurs="1" maxOccurs="1" />
					<xs:element name="math_count" type="xs:integer" minOccurs="1" maxOccurs="1" />
					<xs:element name="spec_count" type="xs:integer" minOccurs="1" maxOccurs="1" />
					<xs:element name="final_count" type="xs:decimal" minOccurs="1" maxOccurs="1" />
				</xs:sequence>
			</xs:complexType>
	</xs:element>
	</xs:schema>

=== Marcos-Oleiro/concursoWEB3/src/lib/candidate_final.xml
<?xml version="1.0" encoding="UTF-8"?>
<candidate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="candidate_final.xsd">
  <registration_number>15497</registration_number>
  <registration_date>2018-01-14</registration_date>
 <position>cargo1</position> 
  <port_teste>
    <pq1>A</pq1>
    <pq2>B</pq2>
    <pq3>B</pq3>
    <pq4>B</pq4>
    <pq5>B</pq5>
    <pq6>B</pq6>
    <pq7>E</pq7>
    <pq8>B</pq8>
    <pq9>B</pq9>
    <pq10>A</pq10>
    <pq11>C</pq11>
    <pq12>E</pq12>
    <pq13>N</pq13>
    <pq14>N</pq14>
    <pq15>A</pq15>
  </port_teste>
  <math_teste>
    <mq1>A</mq1>
    <mq2>B</mq2>
    <mq3>B</mq3>
    <mq4>B</mq4>
    <mq5>B</mq5>
    <mq6>B</mq6>
    <mq7>E</mq7>
    <mq8>B</mq8>
    <mq9>B</mq9>
    <mq10>A</mq10>
    <mq11>C</mq11>
    <mq12>E</mq12>
    <mq13>N</mq13>
    <mq14>N</mq14>
    <mq15>A</mq15>
  </math_teste>
  <spec_teste>
    <sq1>A</sq1>
    <sq2>B</sq2>
    <sq3>B</sq3>
    <sq4>B</sq4>
    <sq5>B</sq5>
    <sq6>B</sq6>
    <sq7>E</sq7>
    <sq8>B</sq8>
    <sq9>B</sq9>
    <sq10>A</sq10>
    <sq11>C</sq11>
    <sq12>E</sq12>
    <sq13>N</sq13>
    <sq14>N</sq14>
    <sq15>A</sq15>
    <sq16>D</sq16>
    <sq17>D</sq17>
    <sq18>E</sq18>
    <sq19>B</sq19>
    <sq20>A</sq20>
  </spec_teste>
  <port_count>0</port_count>
  <math_count>0</math_count>
  <spec_count>0</spec_count>
  <final_count>0.0</final_count>
</candidate>
